In [14]:
import json
import requests
import pandas as pd

In [15]:
chamados = [
    {
        "id": "DEM-001",
        "categoria": "Saneamento Básico",
        "subcategoria": "Lixo não coletado",
        "bairro": "Boa Viagem",
        "latitude": -8.1264,
        "longitude": -34.9036,
        "criadoem": "2026-02-03",
        "status": "Aberto",
        "prioridade": "Alta"
    },
    {
        "id": "DEM-002",
        "categoria": "Infraestrutura",
        "subcategoria": "Buraco na pista",
        "bairro": "Casa Amarela",
        "latitude": -8.0267,
        "longitude": -34.9144,
        "criadoem": "2026-02-05",
        "status": "Em_Andamento",
        "prioridade": "Média"
    },
    {
        "id": "DEM-003",
        "categoria": "Sinalização",
        "subcategoria": "Placa danificada",
        "bairro": "Boa Viagem",
        "latitude": -8.1180,
        "longitude": -34.8998,
        "criadoem": "2026-02-07",
        "status": "Resolvido",
        "prioridade": "Baixa"
    },
    {
        "id": "DEM-004",
        "categoria": "Água e Esgoto",
        "subcategoria": "Esgoto a céu aberto",
        "bairro": "Várzea",
        "latitude": -8.0440,
        "longitude": -34.9440,
        "criadoem": "2026-02-10",
        "status": "Aberto",
        "prioridade": "Alta"
    },
    {
        "id": "DEM-005",
        "categoria": "Iluminação Pública",
        "subcategoria": "Poste apagado",
        "bairro": "Imbiribeira",
        "latitude": -8.1120,
        "longitude": -34.9180,
        "criadoem": "2026-02-12",
        "status": "Fechado",
        "prioridade": "Média"
    },
    {
        "id": "DEM-006",
        "categoria": "Infraestrutura",
        "subcategoria": "Calçada danificada",
        "bairro": "Casa Forte",
        "latitude": -8.0330,
        "longitude": -34.9210,
        "criadoem": "2026-02-15",
        "status": "Aberto",
        "prioridade": "Baixa"
    },
    {
        "id": "DEM-007",
        "categoria": "Saneamento Básico",
        "subcategoria": "Entulho",
        "bairro": "Santo Amaro",
        "latitude": -8.0530,
        "longitude": -34.8890,
        "criadoem": "2026-02-18",
        "status": "Em_Andamento",
        "prioridade": "Alta"
    },
    {
        "id": "DEM-008",
        "categoria": "Água e Esgoto",
        "subcategoria": "Vazamento",
        "bairro": "Madalena",
        "latitude": -8.0630,
        "longitude": -34.9140,
        "criadoem": "2026-02-20",
        "status": "Resolvido",
        "prioridade": "Alta"
    },
    {
        "id": "DEM-009",
        "categoria": "Sinalização",
        "subcategoria": "Faixa apagada",
        "bairro": "Santo Antônio",
        "latitude": -8.0620,
        "longitude": -34.8860,
        "criadoem": "2026-02-23",
        "status": "Aberto",
        "prioridade": "Média"
    },
    {
        "id": "DEM-010",
        "categoria": "Infraestrutura",
        "subcategoria": "Buraco na pista",
        "bairro": "Afogados",
        "latitude": -8.0780,
        "longitude": -34.9050,
        "criadoem": "2026-02-25",
        "status": "Em_Andamento",
        "prioridade": "Alta"
    }
]

In [16]:
df_chamados = pd.DataFrame(chamados)

df_chamados

,id,categoria,subcategoria,bairro,latitude,longitude,criadoem,status,prioridade
0,DEM-001,Saneamento Básico,Lixo não coletado,Boa Viagem,-8.1264,-34.9036,2026-02-03,Aberto,Alta
1,DEM-002,Infraestrutura,Buraco na pista,Casa Amarela,-8.0267,-34.9144,2026-02-05,Em_Andamento,Média
2,DEM-003,Sinalização,Placa danificada,Boa Viagem,-8.1180,-34.8998,2026-02-07,Resolvido,Baixa
3,DEM-004,Água e Esgoto,Esgoto a céu aberto,Várzea,-8.0440,-34.9440,2026-02-10,Aberto,Alta
4,DEM-005,Iluminação Pública,Poste apagado,Imbiribeira,-8.1120,-34.9180,2026-02-12,Fechado,Média
5,DEM-006,Infraestrutura,Calçada danificada,Casa Forte,-8.0330,-34.9210,2026-02-15,Aberto,Baixa
6,DEM-007,Saneamento Básico,Entulho,Santo Amaro,-8.0530,-34.8890,2026-02-18,Em_Andamento,Alta
7,DEM-008,Água e Esgoto,Vazamento,Madalena,-8.0630,-34.9140,2026-02-20,Resolvido,Alta
8,DEM-009,Sinalização,Faixa apagada,Santo Antônio,-8.0620,-34.8860,2026-02-23,Aberto,Média
9,DEM-010,Infraestrutura,Buraco na pista,Afogados,-8.0780,-34.9050,2026-02-25,Em_Andamento,Alta

In [17]:
url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": -8.0631,
    "longitude": -34.8711,
    "start_date": "2026-02-01",
    "end_date": "2026-02-28",
    "daily": "temperature_2m_mean,precipitation_sum",
    "timezone": "America/Recife"
}

response = requests.get(url, params=params)

response.raise_for_status() # Verifica se a requisição foi bem-sucedida, caso contrário, lança uma exceção.

clima = response.json() # Armazena a resposta da API em formato JSON na variável 'clima'.

clima

{'latitude': -8.049209,
 'longitude': -34.923065,
 'generationtime_ms': 5.046725273132324,
 'utc_offset_seconds': -10800,
 'timezone': 'America/Recife',
 'timezone_abbreviation': 'GMT-3',
 'elevation': 12.0,
 'daily_units': {'time': 'iso8601',
  'temperature_2m_mean': '°C',
  'precipitation_sum': 'mm'},
 'daily': {'time': ['2026-02-01',
   '2026-02-02',
   '2026-02-03',
   '2026-02-04',
   '2026-02-05',
   '2026-02-06',
   '2026-02-07',
   '2026-02-08',
   '2026-02-09',
   '2026-02-10',
   '2026-02-11',
   '2026-02-12',
   '2026-02-13',
   '2026-02-14',
   '2026-02-15',
   '2026-02-16',
   '2026-02-17',
   '2026-02-18',
   '2026-02-19',
   '2026-02-20',
   '2026-02-21',
   '2026-02-22',
   '2026-02-23',
   '2026-02-24',
   '2026-02-25',
   '2026-02-26',
   '2026-02-27',
   '2026-02-28'],
  'temperature_2m_mean': [27.6,
   28.0,
   28.2,
   28.5,
   27.1,
   26.6,
   25.4,
   25.8,
   27.3,
   27.5,
   27.6,
   25.2,
   25.4,
   26.0,
   26.0,
   26.6,
   27.2,
   27.2,
   27.7,
   28.0,
   28.3,
   28.5,
   28.0,
   27.3,
   28.3,
   28.4,
   27.7,
   27.7],
  'precipitation_sum': [0.8,
   0.4,
   0.0,
   0.3,
   2.5,
   1.5,
   5.9,
   5.9,
   1.5,
   0.1,
   0.8,
   8.8,
   21.6,
   4.3,
   5.2,
   1.6,
   4.1,
   2.4,
   1.4,
   0.3,
   0.4,
   0.0,
   1.5,
   3.0,
   1.0,
   1.8,
   1.3,
   1.1]}}

In [18]:
# Cria um DataFrame a partir dos dados de clima obtidos da API, contendo as colunas "data", "precipitacao" e "temperatura".
df_clima = pd.DataFrame({
    "data": clima["daily"]["time"],
    "precipitacao": clima["daily"]["precipitation_sum"],
    "temperatura": clima["daily"]["temperature_2m_mean"]
})

df_clima

          data  precipitacao  temperatura
0   2026-02-01           0.8         27.6
1   2026-02-02           0.4         28.0
2   2026-02-03           0.0         28.2
3   2026-02-04           0.3         28.5
4   2026-02-05           2.5         27.1
5   2026-02-06           1.5         26.6
6   2026-02-07           5.9         25.4
7   2026-02-08           5.9         25.8
8   2026-02-09           1.5         27.3
9   2026-02-10           0.1         27.5
10  2026-02-11           0.8         27.6
11  2026-02-12           8.8         25.2
12  2026-02-13          21.6         25.4
13  2026-02-14           4.3         26.0
14  2026-02-15           5.2         26.0
15  2026-02-16           1.6         26.6
16  2026-02-17           4.1         27.2
17  2026-02-18           2.4         27.2
18  2026-02-19           1.4         27.7
19  2026-02-20           0.3         28.0
20  2026-02-21           0.4         28.3
21  2026-02-22           0.0         28.5
22  2026-02-23           1.5         28.0
23  2026-02-24           3.0         27.3
24  2026-02-25           1.0         28.3
25  2026-02-26           1.8         28.4
26  2026-02-27           1.3         27.7
27  2026-02-28           1.1         27.7

In [19]:
df_chamados["data"] = pd.to_datetime(df_chamados["criadoem"]).dt.date # Converte a coluna "criadoem" do dataFeame de Chamados para o tipo datetime e extrai apenas a data, removendo a parte de tempo.

df_clima["data"] = pd.to_datetime(df_clima["data"]).dt.date # Converte a coluna "data" do dataFrame de Clima para o tipo datetime e extrai apenas a data, removendo a parte de tempo.

# df_chamados[["id", "data"]] # Exibe apenas as colunas "id" e "data" do DataFrame de Chamados.
df_clima.head() # Exibe as 5 primeiras linhas do DataFrame de Clima.

         data  precipitacao  temperatura
0  2026-02-01           0.8         27.6
1  2026-02-02           0.4         28.0
2  2026-02-03           0.0         28.2
3  2026-02-04           0.3         28.5
4  2026-02-05           2.5         27.1

In [20]:
# Mescla os DataFrames de Chamados e Clima com base na coluna "data", 
# utilizando um merge do tipo "left" para manter todas as linhas do DataFrame de Chamados e adicionar as informações de clima correspondentes.
#Quando houver uma data correspondente em df_clima, os valores de precipitacao e temperatura
df_final = df_chamados.merge(
    df_clima,
    on="data",
    how="left"
)

df_final # Crição do dataFrame final que contém as informações de chamados e clima mescladas com base na coluna "data".

,id,categoria,subcategoria,bairro,latitude,longitude,criadoem,status,prioridade,data,precipitacao,temperatura
0,DEM-001,Saneamento Básico,Lixo não coletado,Boa Viagem,-8.1264,-34.9036,2026-02-03,Aberto,Alta,2026-02-03,0.0,28.2
1,DEM-002,Infraestrutura,Buraco na pista,Casa Amarela,-8.0267,-34.9144,2026-02-05,Em_Andamento,Média,2026-02-05,2.5,27.1
2,DEM-003,Sinalização,Placa danificada,Boa Viagem,-8.1180,-34.8998,2026-02-07,Resolvido,Baixa,2026-02-07,5.9,25.4
3,DEM-004,Água e Esgoto,Esgoto a céu aberto,Várzea,-8.0440,-34.9440,2026-02-10,Aberto,Alta,2026-02-10,0.1,27.5
4,DEM-005,Iluminação Pública,Poste apagado,Imbiribeira,-8.1120,-34.9180,2026-02-12,Fechado,Média,2026-02-12,8.8,25.2
5,DEM-006,Infraestrutura,Calçada danificada,Casa Forte,-8.0330,-34.9210,2026-02-15,Aberto,Baixa,2026-02-15,5.2,26.0
6,DEM-007,Saneamento Básico,Entulho,Santo Amaro,-8.0530,-34.8890,2026-02-18,Em_Andamento,Alta,2026-02-18,2.4,27.2
7,DEM-008,Água e Esgoto,Vazamento,Madalena,-8.0630,-34.9140,2026-02-20,Resolvido,Alta,2026-02-20,0.3,28.0
8,DEM-009,Sinalização,Faixa apagada,Santo Antônio,-8.0620,-34.8860,2026-02-23,Aberto,Média,2026-02-23,1.5,28.0
9,DEM-010,Infraestrutura,Buraco na pista,Afogados,-8.0780,-34.9050,2026-02-25,Em_Andamento,Alta,2026-02-25,1.0,28.3

In [21]:
# Extract:
# 1. JSON fictício
# 2. API pública Open-Meteo

# Transform:
# 1. JSON → DataFrame
# 2. padronização de datas
# 3. seleção/renomeação de campos
# 4. JOIN entre chamados e clima
# 5. criação do DataFrame final

# Load:
# df_final
#    │
#    ├── MongoDB → dados brutos
#    │
#    └── SQLite  → dados transformados

In [22]:
# Se conectando ao MongoDB para salvar o dataFrame Clima
import os
from dotenv import load_dotenv
from pymongo import MongoClient
from pymongo.server_api import ServerApi

load_dotenv()

mongo_uri = os.getenv("MONGODB_URI")

client = MongoClient(
    mongo_uri,
    server_api=ServerApi("1")
)

In [23]:
client.admin.command("ping") # testando conexão com o MongoDB

{'ok': 1}

In [24]:
# Criando um banco específico para armazenar o dado bruto do dataFrame Clima.
db = client["FISCALIZE_ETL"]

collection = db["clima_raw"]

collection.insert_one(clima)

InsertOneResult(ObjectId('6aa2d0869e4d965db0ed9e0e'), acknowledged=True)

In [25]:
# Testando pra ver se realmente salvou o dado no MongoDB, buscando o primeiro documento da coleção "clima_raw".
documento = collection.find_one()

import pprint

pprint.pp(documento)

{'_id': ObjectId('6aa1a32d63efff2baa4e59c6'),
 'latitude': -8.049209,
 'longitude': -34.923065,
 'generationtime_ms': 4.919290542602539,
 'utc_offset_seconds': -10800,
 'timezone': 'America/Recife',
 'timezone_abbreviation': 'GMT-3',
 'elevation': 12.0,
 'daily_units': {'time': 'iso8601',
                 'temperature_2m_mean': '°C',
                 'precipitation_sum': 'mm'},
 'daily': {'time': ['2026-02-01',
                    '2026-02-02',
                    '2026-02-03',
                    '2026-02-04',
                    '2026-02-05',
                    '2026-02-06',
                    '2026-02-07',
                    '2026-02-08',
                    '2026-02-09',
                    '2026-02-10',
                    '2026-02-11',
                    '2026-02-12',
                    '2026-02-13',
                    '2026-02-14',
                    '2026-02-15',
                    '2026-02-16',
                    '2026-02-17',
                    '2026-02-18',
                    '2026-02-19',
                    '2026-02-20',
                    '2026-02-21',
                    '2026-02-22',
                    '2026-02-23',
                    '2026-02-24',
                    '2026-02-25',
                    '2026-02-26',
                    '2026-02-27',
                    '2026-02-28'],
           'temperature_2m_mean': [27.6,
                                   28.0,
                                   28.2,
                                   28.5,
                                   27.1,
                                   26.6,
                                   25.4,
                                   25.8,
                                   27.3,
                                   27.5,
                                   27.6,
                                   25.2,
                                   25.4,
                                   26.0,
                                   26.0,
                                   26.6,
                                   27.2,
                                   27.2,
                                   27.7,
                                   28.0,
                                   28.3,
                                   28.5,
                                   28.0,
                                   27.3,
                                   28.3,
                                   28.4,
                                   27.7,
                                   27.7],
           'precipitation_sum': [0.8,
                                 0.4,
                                 0.0,
                                 0.3,
                                 2.5,
                                 1.5,
                                 5.9,
                                 5.9,
                                 1.5,
                                 0.1,
                                 0.8,
                                 8.8,
                                 21.6,
                                 4.3,
                                 5.2,
                                 1.6,
                                 4.1,
                                 2.4,
                                 1.4,
                                 0.3,
                                 0.4,
                                 0.0,
                                 1.5,
                                 3.0,
                                 1.0,
                                 1.8,
                                 1.3,
                                 1.1]}}

In [26]:
import sqlite3
conn = sqlite3.connect("fiscalize_etl.db")

# Salvando o DataFrame final no banco de dados SQLite, na tabela "chamados_clima".
df_final.to_sql(
    "chamados_clima",
    conn,
    if_exists="replace",
    index=False
)

conn.close()

In [27]:
#Conferindo o SQLite, abrindo uma conexão e lendo os dados da tabela "chamados_clima" para um DataFrame.
conn = sqlite3.connect("fiscalize_etl.db")

df_teste = pd.read_sql(
    "SELECT * FROM chamados_clima",
    conn
)

conn.close()

df_teste

,id,categoria,subcategoria,bairro,latitude,longitude,criadoem,status,prioridade,data,precipitacao,temperatura
0,DEM-001,Saneamento Básico,Lixo não coletado,Boa Viagem,-8.1264,-34.9036,2026-02-03,Aberto,Alta,2026-02-03,0.0,28.2
1,DEM-002,Infraestrutura,Buraco na pista,Casa Amarela,-8.0267,-34.9144,2026-02-05,Em_Andamento,Média,2026-02-05,2.5,27.1
2,DEM-003,Sinalização,Placa danificada,Boa Viagem,-8.1180,-34.8998,2026-02-07,Resolvido,Baixa,2026-02-07,5.9,25.4
3,DEM-004,Água e Esgoto,Esgoto a céu aberto,Várzea,-8.0440,-34.9440,2026-02-10,Aberto,Alta,2026-02-10,0.1,27.5
4,DEM-005,Iluminação Pública,Poste apagado,Imbiribeira,-8.1120,-34.9180,2026-02-12,Fechado,Média,2026-02-12,8.8,25.2
5,DEM-006,Infraestrutura,Calçada danificada,Casa Forte,-8.0330,-34.9210,2026-02-15,Aberto,Baixa,2026-02-15,5.2,26.0
6,DEM-007,Saneamento Básico,Entulho,Santo Amaro,-8.0530,-34.8890,2026-02-18,Em_Andamento,Alta,2026-02-18,2.4,27.2
7,DEM-008,Água e Esgoto,Vazamento,Madalena,-8.0630,-34.9140,2026-02-20,Resolvido,Alta,2026-02-20,0.3,28.0
8,DEM-009,Sinalização,Faixa apagada,Santo Antônio,-8.0620,-34.8860,2026-02-23,Aberto,Média,2026-02-23,1.5,28.0
9,DEM-010,Infraestrutura,Buraco na pista,Afogados,-8.0780,-34.9050,2026-02-25,Em_Andamento,Alta,2026-02-25,1.0,28.3

In [28]:
#"Na etapa de Extract, os dados da API são obtidos em seu formato original. 
# Na etapa de Load, esse resultado bruto é preservado no MongoDB. 
# Após a transformação e integração com os chamados, o DataFrame resultante é persistido no SQLite."