In [27]:
# 1 - acessando a fonte;
# 2 - verificando se ela respondeu;
# 3 - descobrindo o recurso disponível;
# 4 - depois vamos selecionar o arquivo de Pernambuco;
# 5 - carregar os dados;
# 3 - descobrir quais colunas representam a população.

In [28]:
import pandas as pd
import requests

In [29]:
url = "https://ftp.ibge.gov.br/Censos/Censo_Demografico_2022/Agregados_por_Setores_Censitarios/Agregados_por_Bairro_csv/"

response = requests.get(url)

response.raise_for_status()

print(response.status_code)

#Fonte respondeu 200

200

In [30]:
print(response.text[:5000])

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /Censos/Censo_Demografico_2022/Agregados_por_Setores_Censitarios/Agregados_por_Bairro_csv</title>
 </head>
 <body>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<div>
    <div class="max-width topo">
        <a href="https://www.ibge.gov.br/">
            <img class="logo" src="https://www.ibge.gov.br/explica/images/logo.jpg" alt="Logo IBGE" />
        </a>
        <form target="_blank" class="busca" action="https://www.ibge.gov.br/busca.html">
            <label for="ibgeSearch" style="display: block;text-indent: -99999999px;font-size: 0;opacity: 0;">Busque no
                Portal IBGE</label>
            <input type="hidden" name="searchphrase" value="all" />
            <input id="ibgeSearch" class="busca-campo" name="searchword" type="search"
                placeholder="Buscar no Portal IBGE">
            <input class="busca-botao" type="submit" value="Buscar">
        </form>
    </div>

    <div class="titulo sem-busca sem-dados">
        <h1 class="content-width">Downloads | Estatísticas</h1>
    </div>

</div>

<div
    style="padding: 0;border-radius: 6px;margin: 20px auto 30px;font-family: &quot;Open Sans&quot;, Arial, sans-serif;max-width: 850px;text-align: center;">
    <p style="text-align: center;font-size: 18px;">
        Todos os arquivos aqui dispon&iacute;veis s&atilde;o p&uacute;blicos.
    </p>
</div>

<style>
    html,
    body,
    p,
    ol,
    ul,
    li,
    dl,
    dt,
    dd,
    blockquote,
    figure,
    fieldset,
    legend,
    textarea,
    pre,
    iframe,
    hr,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        font-family: 'Open Sans', sans-serif;
        margin: 0;
        padding: 0;
        color: #6b6b6f;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        font-size: 100%;
        font-weight: normal
    }

    ul {
        list-style: none
    }

    button,
    input,
    select,
    textarea {
        margin: 0;
    }

    html {
        box-sizing: border-box
    }

    *,
    *:before,
    *:after {
        box-sizing: inherit
    }

    img,
    embed,
    iframe,
    object,
    video {
        height: auto;
        max-width: 100%
    }

    audio {
        max-width: 100%
    }

    iframe {
        border: 0;
        width: 100%;
        height: 450px;
    }

    table {
        border-collapse: collapse;
        border-spacing: 0
    }

    td,
    th {
        padding: 0;
        text-align: left
    }

    .clearfix:after {
        content: ".";
        visibility: hidden;
        display: block;
        height: 0;
        clear: both;
    }

    .hide {
        display: none;
    }

    /* ESTRUTURA */

    .max-width,
    .content-width {
        width: 100%;
        margin: 0 auto;
    }

    .max-width {
        max-width: 850px;
    }

    .content-width {
        max-width: 800px;
        position: relative;
    }

    input,
    select {
        height: 32px;
        width: 100%;
        padding: 5px 13px;
        font-size: 14px;
        background: #ffffff;
        border: 1px solid #e0dfdf;
        border-radius: 4px;
    }

    input[type=submit],
    button {
        height: 32px;
        padding: 5px 13px;
        border: 0;
        border-radius: 3px;
        transition: background-color 150ms linear;
        cursor: pointer;
    }

    h2 {
        font-size: 20px;
        font-weight: 700;
        margin: 25px 0 12px;
        color: #211915;
    }

    h2:first-child {
        margin: 0 0 12px;
    }

    h2.saiba-mais-titulo {
        background: #1a84ad;
        padding: 15px 25px;
        font-size: 20px;
        border-radius: 10px 10px 0 0;
        font-weight: 700;
        margin: 25px 0 0;
        color: #ffffff;
    }

    h3 {
        font-size: 16px;
        font-weight: 700;
        margin: 25px 0 12px;
        color: #e4853c;
    }

    h4 {
        font-weight: 700;
        margin-bottom: 10px;
        color: #eb9c5a;
    }

    @media only screen and (max-width: 1200px) {

        .max-width,
        .content-width {
            padding: 0 25px;
        }
    }


    /* HEADER */

    .logo {
        width: 160px;
    }

    .topo {
        height: auto;
        padding: 40px 0;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .busca {
        width: 215px;
        float: right;
        position: relative;
        padding: 5px 0px;
        margin: 0;
    }

    .busca-campo {
        background: #f0efef;
        border: 1px solid #e0dfdf;
    }

    .busca-botao {
        width: 35px;
        font-size: 0;
        background: #0c326f url(https://www.ibge.gov.br/explica/images/busca.png) no-repeat center center/15px;
        border-radius: 0 3px 3px 0;
        position: absolute;
        top: 5px;
        right: 0;
    }

    .busca-botao:hover {
        background-color: #0c652d;
    }

    .titulo {
        clear: both;
        float:

In [31]:

#Explorando o conteúdo da página para descobrir os arquivos disponíveis.
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

arquivos = [
    link.get("href")
    for link in soup.find_all("a")
]

arquivos

['https://www.ibge.gov.br/',
 '?C=N;O=D',
 '?C=M;O=A',
 '?C=S;O=A',
 '?C=D;O=A',
 '/Censos/Censo_Demografico_2022/Agregados_por_Setores_Censitarios/',
 'Agregados_por_bairros_alfabetizacao_BR.zip',
 'Agregados_por_bairros_basico_BR_20260520.zip',
 'Agregados_por_bairros_caracteristicas_domicilio1_BR.zip',
 'Agregados_por_bairros_caracteristicas_domicilio2_BR_20250417.zip',
 'Agregados_por_bairros_caracteristicas_domicilio3_BR_20250417.zip',
 'Agregados_por_bairros_cor_ou_raca_BR.zip',
 'Agregados_por_bairros_demografia_BR.zip',
 'Agregados_por_bairros_domicilios_indigenas_BR.zip',
 'Agregados_por_bairros_domicilios_quilombolas_BR.zip',
 'Agregados_por_bairros_obitos_BR.zip',
 'Agregados_por_bairros_parentesco_BR.zip',
 'Agregados_por_bairros_pessoas_indigenas_BR.zip',
 'Agregados_por_bairros_pessoas_quilombolas_BR.zip',
 'https://www.ibge.gov.br/',
 'http://www.facebook.com/ibgeoficial',
 'https://instagram.com/ibgeoficial',
 'https://www.tiktok.com/@ibgeoficial',
 'https://twitter.com/ibgecomunica',
 'http://www.youtube.com/ibgeoficial']

In [32]:
url_demografia = url.rstrip("/") + "/" + "Agregados_por_bairros_demografia_BR.zip"

print(url_demografia)

https://ftp.ibge.gov.br/Censos/Censo_Demografico_2022/Agregados_por_Setores_Censitarios/Agregados_por_Bairro_csv/Agregados_por_bairros_demografia_BR.zip

In [33]:
response_demografia = requests.get(url_demografia)

print(response_demografia.status_code)

200

In [34]:
# Baixando o arquivo de demografia
# URL do IBGE
#    ↓
# requests.get()
#    ↓
# conteúdo do ZIP
#    ↓
# memória do notebook
response_demografia = requests.get(url_demografia)

response_demografia.raise_for_status() # Verifica se deu certo (200)

arquivo_zip = response_demografia.content

print(f"Tamanho do arquivo: {len(arquivo_zip) / (1024 * 1024):.2f} MB")

Tamanho do arquivo: 1.25 MB

In [35]:
# biblioteca para lidar com arquivos ZIP nativa do Python
import zipfile
import io

zip_ibge = zipfile.ZipFile(io.BytesIO(arquivo_zip))

zip_ibge.namelist()

['Agregados_por_bairros_demografia_BR.csv']

In [36]:
# Ler o arquivo zip com pandas
df_demografia = pd.read_csv(
    zip_ibge.open("Agregados_por_bairros_demografia_BR.csv"),
    sep=";",
    encoding="latin1"
)

df_demografia.head()
# df_demografia.shape
# df_demografia.columns.tolist()

# No próprio dicionário do IBGE a coluna V01006 é a de "Quantidade de moradoes"

,CD_BAIRRO,NM_BAIRRO,V01006,V01007,V01008,V01009,V01010,V01011,V01012,V01013,...,V01032,V01033,V01034,V01035,V01036,V01037,V01038,V01039,V01040,V01041
0,1100015001,Centro,1213,575,638,30,30,37,56,40,...,69,75,97,79,83,145,190,168,154,92
1,1100015002,Liberdade,1029,502,527,37,35,33,52,40,...,67,60,95,81,73,155,153,122,68,73
2,1100015003,Cidade Alta,1288,605,683,57,39,46,37,40,...,93,88,76,98,109,189,207,163,97,64
3,1100015005,Princesa Isabel,2846,1443,1403,112,111,130,131,117,...,208,229,248,214,212,434,397,322,216,163
4,1100015006,Redondo,2360,1114,1246,74,82,80,93,103,...,160,174,186,184,181,357,353,270,194,133

In [ ]:

# Parâmetros para filtrar os dados de Recife!! Os bairros e população
# V01006 = Quantidade de moradores
# codigo_recife = 2611606 (RECIFE)

SyntaxError: invalid syntax (2312305777.py, line 2)

In [68]:
# Validando se o código do município está correto
df_populacao = df_demografia[
    ["CD_BAIRRO", "NM_BAIRRO", "V01006"]
]

df_populacao

        CD_BAIRRO           NM_BAIRRO V01006
0      1100015001              Centro   1213
1      1100015002           Liberdade   1029
2      1100015003         Cidade Alta   1288
3      1100015005     Princesa Isabel   2846
4      1100015006             Redondo   2360
...           ...                 ...    ...
17571  5218300009      Setor Mãe Bela   3045
17572  5218300010  Setor Buenos Aires   9251
17573  5218300011         Cafelândios    600
17574  5218300012   Vale do Amanhecer    902
17575  5218300013       Vila São José   1527

[17576 rows x 3 columns]

In [69]:
codigo_recife = "2611606"

df_recife = df_populacao[
    df_populacao["CD_BAIRRO"]
    .astype(str)
    .str.startswith(codigo_recife)
]

df_recife.head()
df_recife.shape
df_recife[["CD_BAIRRO", "NM_BAIRRO", "V01006"]]

       CD_BAIRRO         NM_BAIRRO  V01006
4281  2611606001            Recife     537
4282  2611606002       Santo Amaro   27103
4283  2611606003         Boa Vista   13095
4284  2611606004          Soledade    2081
4285  2611606005     Santo Antônio     447
...          ...               ...     ...
4370  2611606090             Ipsep   20610
4371  2611606091       Imbiribeira   52153
4372  2611606092        Boa Viagem  125755
4373  2611606093              Pina   29195
4374  2611606094  Brasília Teimosa   16685

[94 rows x 3 columns]

In [39]:
chamados = [
    {
        "id": "DEM-001",
        "categoria": "Saneamento Básico",
        "subcategoria": "Lixo não coletado",
        "bairro": "Boa Viagem",
        "latitude": -8.1264,
        "longitude": -34.9036,
        "criadoem": "2026-02-03",
        "status": "Aberto",
        "prioridade": "Alta"
    },
    {
        "id": "DEM-002",
        "categoria": "Infraestrutura",
        "subcategoria": "Buraco na pista",
        "bairro": "Casa Amarela",
        "latitude": -8.0267,
        "longitude": -34.9144,
        "criadoem": "2026-02-05",
        "status": "Em_Andamento",
        "prioridade": "Média"
    },
    {
        "id": "DEM-003",
        "categoria": "Sinalização",
        "subcategoria": "Placa danificada",
        "bairro": "Boa Viagem",
        "latitude": -8.1180,
        "longitude": -34.8998,
        "criadoem": "2026-02-07",
        "status": "Resolvido",
        "prioridade": "Baixa"
    },
    {
        "id": "DEM-004",
        "categoria": "Água e Esgoto",
        "subcategoria": "Esgoto a céu aberto",
        "bairro": "Várzea",
        "latitude": -8.0440,
        "longitude": -34.9440,
        "criadoem": "2026-02-10",
        "status": "Aberto",
        "prioridade": "Alta"
    },
    {
        "id": "DEM-005",
        "categoria": "Iluminação Pública",
        "subcategoria": "Poste apagado",
        "bairro": "Imbiribeira",
        "latitude": -8.1120,
        "longitude": -34.9180,
        "criadoem": "2026-02-12",
        "status": "Fechado",
        "prioridade": "Média"
    },
    {
        "id": "DEM-006",
        "categoria": "Infraestrutura",
        "subcategoria": "Calçada danificada",
        "bairro": "Casa Forte",
        "latitude": -8.0330,
        "longitude": -34.9210,
        "criadoem": "2026-02-15",
        "status": "Aberto",
        "prioridade": "Baixa"
    },
    {
        "id": "DEM-007",
        "categoria": "Saneamento Básico",
        "subcategoria": "Entulho",
        "bairro": "Santo Amaro",
        "latitude": -8.0530,
        "longitude": -34.8890,
        "criadoem": "2026-02-18",
        "status": "Em_Andamento",
        "prioridade": "Alta"
    },
    {
        "id": "DEM-008",
        "categoria": "Água e Esgoto",
        "subcategoria": "Vazamento",
        "bairro": "Madalena",
        "latitude": -8.0630,
        "longitude": -34.9140,
        "criadoem": "2026-02-20",
        "status": "Resolvido",
        "prioridade": "Alta"
    },
    {
        "id": "DEM-009",
        "categoria": "Sinalização",
        "subcategoria": "Faixa apagada",
        "bairro": "Santo Antônio",
        "latitude": -8.0620,
        "longitude": -34.8860,
        "criadoem": "2026-02-23",
        "status": "Aberto",
        "prioridade": "Média"
    },
    {
        "id": "DEM-010",
        "categoria": "Infraestrutura",
        "subcategoria": "Buraco na pista",
        "bairro": "Afogados",
        "latitude": -8.0780,
        "longitude": -34.9050,
        "criadoem": "2026-02-25",
        "status": "Em_Andamento",
        "prioridade": "Alta"
    }
]

In [40]:
df_chamados = pd.DataFrame(chamados)

df_chamados

,id,categoria,subcategoria,bairro,latitude,longitude,criadoem,status,prioridade
0,DEM-001,Saneamento Básico,Lixo não coletado,Boa Viagem,-8.1264,-34.9036,2026-02-03,Aberto,Alta
1,DEM-002,Infraestrutura,Buraco na pista,Casa Amarela,-8.0267,-34.9144,2026-02-05,Em_Andamento,Média
2,DEM-003,Sinalização,Placa danificada,Boa Viagem,-8.1180,-34.8998,2026-02-07,Resolvido,Baixa
3,DEM-004,Água e Esgoto,Esgoto a céu aberto,Várzea,-8.0440,-34.9440,2026-02-10,Aberto,Alta
4,DEM-005,Iluminação Pública,Poste apagado,Imbiribeira,-8.1120,-34.9180,2026-02-12,Fechado,Média
5,DEM-006,Infraestrutura,Calçada danificada,Casa Forte,-8.0330,-34.9210,2026-02-15,Aberto,Baixa
6,DEM-007,Saneamento Básico,Entulho,Santo Amaro,-8.0530,-34.8890,2026-02-18,Em_Andamento,Alta
7,DEM-008,Água e Esgoto,Vazamento,Madalena,-8.0630,-34.9140,2026-02-20,Resolvido,Alta
8,DEM-009,Sinalização,Faixa apagada,Santo Antônio,-8.0620,-34.8860,2026-02-23,Aberto,Média
9,DEM-010,Infraestrutura,Buraco na pista,Afogados,-8.0780,-34.9050,2026-02-25,Em_Andamento,Alta

In [41]:
# Contar quantos chamados existem em cada bairro

df_chamados_por_bairro = (
    df_chamados
    .groupby("bairro")
    .size()
    .reset_index(name="chamados")
)

df_chamados_por_bairro

          bairro  chamados
0       Afogados         1
1     Boa Viagem         2
2   Casa Amarela         1
3     Casa Forte         1
4    Imbiribeira         1
5       Madalena         1
6    Santo Amaro         1
7  Santo Antônio         1
8         Várzea         1

In [43]:
df_populacao_recife = df_recife[
    ["CD_BAIRRO", "NM_BAIRRO", "V01006"]
].copy()

df_populacao_recife

       CD_BAIRRO         NM_BAIRRO  V01006
4281  2611606001            Recife     537
4282  2611606002       Santo Amaro   27103
4283  2611606003         Boa Vista   13095
4284  2611606004          Soledade    2081
4285  2611606005     Santo Antônio     447
...          ...               ...     ...
4370  2611606090             Ipsep   20610
4371  2611606091       Imbiribeira   52153
4372  2611606092        Boa Viagem  125755
4373  2611606093              Pina   29195
4374  2611606094  Brasília Teimosa   16685

[94 rows x 3 columns]

In [46]:
df_populacao_recife = df_populacao_recife.rename(
    columns={
        "CD_BAIRRO": "codigo_bairro",
        "NM_BAIRRO": "bairro",
        "V01006": "populacao"
    }
)

df_populacao_recife

      codigo_bairro            bairro populacao
4281     2611606001            Recife       537
4282     2611606002       Santo Amaro     27103
4283     2611606003         Boa Vista     13095
4284     2611606004          Soledade      2081
4285     2611606005     Santo Antônio       447
...             ...               ...       ...
4370     2611606090             Ipsep     20610
4371     2611606091       Imbiribeira     52153
4372     2611606092        Boa Viagem    125755
4373     2611606093              Pina     29195
4374     2611606094  Brasília Teimosa     16685

[94 rows x 3 columns]

In [ ]:
# Padronizando os nomes dos bairros para facilitar a junção dos DataFrames

df_chamados_por_bairro["bairro"] = (
    df_chamados_por_bairro["bairro"]
    .str.strip()
    .str.upper()
)

df_populacao_recife["bairro"] = (
    df_populacao_recife["bairro"]
    .str.strip()
    .str.upper()
)

In [54]:
# Merge dos DataFrames para unir os dados de chamados e população por bairro

df_bairros = df_chamados_por_bairro.merge(
    df_populacao_recife[["codigo_bairro", "bairro", "populacao"]],
    on="bairro",
    how="left"
)

df_bairros

          bairro  chamados  codigo_bairro populacao
0       AFOGADOS         1     2611606075     31457
1     BOA VIAGEM         2     2611606092    125755
2   CASA AMARELA         1     2611606048     32450
3     CASA FORTE         1     2611606055      6307
4    IMBIRIBEIRA         1     2611606091     52153
5       MADALENA         1     2611606062     25774
6    SANTO AMARO         1     2611606002     27103
7  SANTO ANTÔNIO         1     2611606005       447
8         VÁRZEA         1     2611606069     70938

In [58]:
df_bairros["populacao"] = pd.to_numeric(
    df_bairros["populacao"],
    errors="coerce"
)

In [ ]:
df_bairros["chamados_por_1000"] = (
    df_bairros["chamados"] / df_bairros["populacao"]
) * 1000


df_bairros["chamados_por_1000"] = (
    df_bairros["chamados_por_1000"]
    .round(2)
)

#"Boa Viagem teve X chamados para cada 1.000 habitantes.!"
# Isso torna a comparação entre bairros muito mais justa, porque um bairro grande 
# naturalmente tende a ter mais chamados simplesmente por ter mais moradores.

In [62]:
df_bairros

          bairro  chamados  codigo_bairro  populacao  chamados_por_1000
0       AFOGADOS         1     2611606075      31457               0.03
1     BOA VIAGEM         2     2611606092     125755               0.02
2   CASA AMARELA         1     2611606048      32450               0.03
3     CASA FORTE         1     2611606055       6307               0.16
4    IMBIRIBEIRA         1     2611606091      52153               0.02
5       MADALENA         1     2611606062      25774               0.04
6    SANTO AMARO         1     2611606002      27103               0.04
7  SANTO ANTÔNIO         1     2611606005        447               2.24
8         VÁRZEA         1     2611606069      70938               0.01

In [67]:
# Etapa de Load!

import os
from dotenv import load_dotenv
from pymongo import MongoClient
from pymongo.server_api import ServerApi

load_dotenv()

mongo_uri = os.getenv("MONGODB_URI")

client = MongoClient(
    mongo_uri,
    server_api=ServerApi("1")
)

client.admin.command("ping")

print("Conexão com MongoDB realizada com sucesso!")

Conexão com MongoDB realizada com sucesso!

In [ ]:
# Vamos guardar o dataFrame da população total do IBGE!
# Criando banco da coleção e inserindo os dados do DataFrame no MongoDB

db = client["FISCALIZE_ETL"]

collection = db["populacao_ibge_raw"]

dados_brutos = df_demografia.to_dict(orient="records")
resultado = collection.insert_many(dados_brutos)

print(f"Registros inseridos: {len(resultado.inserted_ids)}")

Registros inseridos: 17576

In [76]:
print(collection.count_documents({}))
collection.find_one()

17576

{'_id': ObjectId('6aa20eacf4a8ba23ab44854b'),
 'CD_BAIRRO': 1100015001,
 'NM_BAIRRO': 'Centro',
 'V01006': '1213',
 'V01007': '575',
 'V01008': '638',
 'V01009': '30',
 'V01010': '30',
 'V01011': '37',
 'V01012': '56',
 'V01013': '40',
 'V01014': '36',
 'V01015': '70',
 'V01016': '75',
 'V01017': '80',
 'V01018': '70',
 'V01019': '51',
 'V01020': '31',
 'V01021': '39',
 'V01022': '38',
 'V01023': '41',
 'V01024': '39',
 'V01025': '47',
 'V01026': '75',
 'V01027': '115',
 'V01028': '88',
 'V01029': '84',
 'V01030': '41',
 'V01031': '61',
 'V01032': '69',
 'V01033': '75',
 'V01034': '97',
 'V01035': '79',
 'V01036': '83',
 'V01037': '145',
 'V01038': '190',
 'V01039': '168',
 'V01040': '154',
 'V01041': '92'}

In [77]:
# Vamos adicionar no SQLite coleção de chamados por bairro,
# com a população e a taxa de chamados por 1.000 habitantes.

import sqlite3

conn = sqlite3.connect("fiscalize_etl.db")

df_bairros.to_sql(
    "chamados_populacao",
    conn,
    if_exists="replace",
    index=False
)

conn.close()